### ISSUE TITLE
[Bug]: OrderMgr class content is broken

### ISSUE THREAD

**Issue by clavery** [sfccdevops/sfcc-docs#1]
### Issue Checklist:

- [X] No matching [Open Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aopen)
- [X] No matching [Closed Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### What happened?

Check `class OrderMgr`. Some funky stuff happening on that page, looks like parsing/scraping failed on something early and wrapped a bunch of things in a code block.

### Which Browser(s) were you using?

Chrome

### Which Operating System(s) were you using?

macOS

### Steps to produce this issue.

visit search OrderMgr

![Screenshot 2023-09-08 at 11 12 37 PM](https://github.com/sfccdevops/sfcc-docs/assets/88399/0302b147-4592-4dce-88ad-a4616178b103)

**Comment by manifestinteractive** [comment]
Fixed in v0.2.0 release
