### ISSUE TITLE
[Feature Request / Suggestion]: 

### ISSUE THREAD

**Issue by jbachelet** [sfccdevops/sfcc-docs#19]
### Issue Checklist:

- [X] There are no matching [Open Feature Requests](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Feature+Request"+is%3Aopen)
- [X] There are no matching [Closed Feature Requests](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Feature+Request"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### Suggestion / Feature Request

Hello,

First of all, THANK YOU for this awesome job!

Once great feature request might be to have dedicated URLs for searching search terms.
For example, having https://sfccdocs.com/q?ordermgr might show a result page with everything matching `ordermgr` within the docs.

This would be very helpful as one could then configure your website as a search engine within the browser, and so being able to search anything from the docs fairly easily!
Also useful to share links of search results.

Thank you!

**Comment by manifestinteractive** [comment]
Did you see this on the home page?

```
Easily search the docs from external tools using the following URL. Just replace <keyword> with your URL encoded search term.

https://sfccdocs.com/?q=<keyword>
```

It's not a "search results" solution, but does take you directly to the first matching result.

If you'd like a results page, we can keep this request open too see if other want this as well. 

But if you're ok just going to the best result, that's already done

Only thing missing in your URL was the equal sign after the q, and you would have gotten that working.

e.g.

https://sfccdocs.com/?q=ordermgr

**Comment by manifestinteractive** [comment]
Closing this since the feature exists :)
