### ISSUE TITLE
[External Search] Error message when searching an inexisting term

### ISSUE THREAD

**Issue by christophe-bouchy** [sfccdevops/sfcc-docs#23]
### Issue Checklist:

- [X] No matching [Open Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aopen)
- [X] No matching [Closed Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### What happened?

Hello (and thanks for your work 👍),

While adding sfcc-docs as my default SFCC Search Engine on my browser (using url `https://sfccdocs.com/?q=%s`), I've noticed an error when submitting on inexisting term : 

> Application error: a client-side exception has occurred (see the browser console for more information).

The console provides the following error : 

> TypeError: Cannot read properties of undefined (reading 'url')

Finally, I can't reproduce this issue on the site with a direct internal search, it's seems only related to external search process.

Thanks in advance for your time :-)
Christophe

### Which Browser(s) were you using?

Chrome

### Which Operating System(s) were you using?

Windows

### Steps to produce this issue.

Simulate an external search by cliking the link below (containing a wrong search term) :

> https://sfccdocs.com/?q=slocontent

**Comment by manifestinteractive** [comment]
Ah. It looks like this is happening because there is no search results for your keyword ( looks like a typo )

But that's still a bug. Should show a no results screen for that use case.

Adding back the t in slot you get the intended action. 

https://sfccdocs.com/?q=slotcontent

**Comment by christophe-bouchy** [comment]
Yes sure, it was clearly a typo when I typed it too quickly.
But, as it made me experience this error screen, I prefered declare it as a bug here, just in case.

I confirm an external search with "slotcontent" works as expected :-)
