### ISSUE TITLE
More context in Search Results

### ISSUE THREAD

**Issue by manifestinteractive** [sfccdevops/sfcc-docs#4]
### Issue Checklist:

- [X] There are no matching [Open Requested Changes](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Requested+Change"+is%3Aopen)
- [X] There are no matching [Closed Requested Changes](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Requested+Change"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### Describe the Problem

Sometimes search results come back for multiple matches, but they look nearly identical ( even though they are different pages ) because of how they are listed and just showing the area where the match existed.

### Describe the Solution

It would be be nice to be able to quickly have more context about the search result to so I could more easily tell the difference between which one is more relevant to my search.

**Comment by ast-istarikov** [comment]
One more issue with the search - it doesn't point out to the specific search term - but the page in general
Please see the example in screencast

[screencast-sfccdocs.com-2023.09.11-09_58_48.webm](https://github.com/sfccdevops/sfcc-docs/assets/45293754/5381702f-a3ee-43ef-9620-a5a607a9ced6)

**Comment by manifestinteractive** [comment]
This has been resolved in v0.3.0 which is now available at https://sfccdocs.com

![Screenshot 2023-09-17 at 5 41 41 AM](https://github.com/sfccdevops/sfcc-docs/assets/508411/2ca86ae9-1f56-4c7f-914a-f98c0c2ea1ac)
