### ISSUE TITLE
[Bug]: 404 Error on navigating back and forth to a page opened by using the search bar

### ISSUE THREAD

**Issue by Ritesh-Chandra-Roy** [sfccdevops/sfcc-docs#6]
### Issue Checklist:

- [X] No matching [Open Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aopen)
- [X] No matching [Closed Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### What happened?

<img width="611" alt="image" src="https://github.com/sfccdevops/sfcc-docs/assets/86686009/7dc7fade-44f9-44e2-b2b2-fe82c194839f">

### Which Browser(s) were you using?

Microsoft Edge

### Which Operating System(s) were you using?

Windows

### Steps to produce this issue.

Steps to reproduce:-

1. Search the SFCC Docs for a class or something by pressing CTRL + K.
2. When the page has loaded, navigate back to the last page.
3. A 404 Error is expected.

**Comment by manifestinteractive** [comment]
Hey @Ritesh-Chandra-Roy , thanks for catching this.

100% forgot to set default route on nginx config, so if you started on home page things were fine, but if you tried to access a URL directly, ya, it was not being mapped to the root index.html.

This is now resolved and you can visit a link directly.
