### ISSUE TITLE
[Bug]: Product Search Results Not Relevant

### ISSUE THREAD

**Issue by davidlinke** [sfccdevops/sfcc-docs#7]
### Issue Checklist:

- [X] No matching [Open Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aopen)
- [X] No matching [Closed Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### What happened?

Searching for `class product` or `product` does not bring up the product class in the first results. I would expect it to be the first result.

<img width="645" alt="Screenshot 2023-09-11 at 9 06 18 AM" src="https://github.com/sfccdevops/sfcc-docs/assets/51678914/d4f24942-d513-4757-b447-c5c3ebb3d63b">
<img width="625" alt="Screenshot 2023-09-11 at 9 06 38 AM" src="https://github.com/sfccdevops/sfcc-docs/assets/51678914/f4e33a9e-3f69-4867-b971-13cd8020d265">

### Which Browser(s) were you using?

Safari

### Which Operating System(s) were you using?

macOS

### Steps to produce this issue.

1. Select Search
2. Type in `class product` or `product` and observe the irrelevant results

**Comment by manifestinteractive** [comment]
This has been resolved in v0.3.0 which is now available at https://sfccdocs.com

![Screenshot 2023-09-17 at 5 40 33 AM](https://github.com/sfccdevops/sfcc-docs/assets/508411/5aa4cec3-8039-48f2-abd5-9b8e34fac5a5)
