### ISSUE TITLE
[Bug]: Searching for partial method names fails

### ISSUE THREAD

**Issue by sholsinger** [sfccdevops/sfcc-docs#8]
### Issue Checklist:

- [X] No matching [Open Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aopen)
- [X] No matching [Closed Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### What happened?

Let's say you forget the exact name of a method, but you know the first part of it.
For example: `Session.setTrackingAllowed` 

You'll end up with no hits that match partially in this case. Perhaps because of an exact match on the `TrackingInfo` object. 

<img width="689" alt="Screenshot 2023-09-11 at 12 38 39 PM" src="https://github.com/sfccdevops/sfcc-docs/assets/435501/c250b0c4-154a-4eab-9563-0171f41ca3e2">

### Which Browser(s) were you using?

Chrome

### Which Operating System(s) were you using?

macOS

### Steps to produce this issue.

Step 1: Type `setTracking` into the search field
Step 2: Press 'enter' key
Step 3: Observe that the `Session` class isn't a hit.

**Comment by manifestinteractive** [comment]
This has been resolved in v0.3.0 which is now available at https://sfccdocs.com

![Screenshot 2023-09-17 at 5 12 36 AM](https://github.com/sfccdevops/sfcc-docs/assets/508411/f9af1e78-8b01-4361-9e20-0c4335bee6e1)
